spring:
  datasource:
    url: jdbc:postgresql://jmml.ml:5432/nurse_app_db
    username: jmml
    password: siyaexisteparaquecrear
    platform: postgresql
    driverClassName: org.postgresql.Driver
server :
  port : 8585
  servlet :
    context-path : /nurseapp-api/v1